### ISSUE TITLE
Error on CLI

### ISSUE THREAD

**Issue by marianvlad** [tusharmath/Multi-threaded-downloader#113]
I use nodejs 5.11.0 and I have this error in terminal.

~~~
/usr/lib/node_modules/mt-downloader/.dist/bin/mtd.js:50
  const [{ size$, completion$, invalidOptions$, validOptions$ }] = (0, _muxer.demux)(signal$, 'size$', 'completion$', 'invalidOptions$', 'validOptions$');
        ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
~~~

**Comment by marianvlad** [comment]
Old nodejs version. Solved.
