### ISSUE TITLE
Error: The .mtd file is corrupt. Start a new download??

### ISSUE THREAD

**Issue by renjithaccel** [tusharmath/Multi-threaded-downloader#154]
Hi,

I'm getting this error while running the sample download scripts. I saw an .mtd file is creating on my destination directory. After few seconds it is failing. The error is

Error: The .mtd file is corrupt. Start a new download.
    at module.exports (/home/testmachine/node_modules/mt-downloader/lib/Exceptions.js:83:33)
    at /home/testmachine/node_modules/mt-downloader/lib/core/DownloadReaderAsyncTask.js:36:13
    at FSReqWrap.wrapper [as oncomplete] (fs.js:602:17)

**Comment by tusharmath** [comment]
@renjithaccel I am not sure if you are on the right version. Current stable version is `2.2.2`

**Comment by renjithaccel** [comment]
Hi,

I have upgraded to v​2.2.2​
​
​. Tried to run the sample code given ​in here
<https://www.npmjs.com/package/mt-downloader#new-downloads>.

var downloader = createDownload({path, url});

TypeError: createDownload is not a function
    at Object.<anonymous> (/home/testPc/Samples/down.js:8:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

I'm new to NodeJs and I couldn't find out the reason of this error. You
have any idea??

Thanks

**Comment by tusharmath** [comment]
@renjithaccel There was some issue with npm's website, it never gets the latest README file. You must checkout the documentation here — https://github.com/tusharmath/Multi-threaded-downloader
