### ISSUE TITLE
Implementing ProgressBar with progress update

### ISSUE THREAD

**Issue by ArkeologeN** [tusharmath/Multi-threaded-downloader#189]
I've the following code to download file:
```
const options = {
      url: file.download,
      path: dest
    };

    const createMTDFile$ = CreateMTDFile(options).share();
    const [{ fdW$ }] = demux(createMTDFile$, 'fdW$');

    /**
     * Download From MTD File
     */
    const downloadFromMTDFile$ = createMTDFile$
      .last()
      .map(MTDPath(options.path))
      .flatMap(DownloadFromMTDFile).share();

    const [{ fdR$, meta$ }] = demux(downloadFromMTDFile$, 'meta$', 'fdR$');

    /**
     * Finalize Downloaded FILE
     */
    const finalizeDownload$ = downloadFromMTDFile$.last()
      .withLatestFrom(fdR$, meta$, (_: {}, fd: {}, meta: {}) => ({
        fd$: O.just(fd),
        meta$: O.just(meta)
      }))
      .flatMap(FinalizeDownload)
      .share()
      .last();

    /**
     * Close File Descriptors
     */
    const fd$ = finalizeDownload$
      .withLatestFrom(fdW$, fdR$)
      .map(R.tail)
      .flatMap(R.map(R.of));
    const closeFile = FILE.close(fd$).toPromise();
```

However, I'm not sure how to use `ProgressBar` with this. I tried to do:
```
const bar = new Progress(':percent :bar', {
  total: 1000,
  complete: '█',
  incomplete: '░'
})
Completion(meta$).subscribe((i) => bar.update(i))
```

but this throws: 
```
TypeError: progress_1.default is not a constructor
```

Do you have an idea or any updated guide? thanks!

**Comment by ArkeologeN** [comment]
PS: I solved the above problem. It seems `.subscribe` on `Observable` doesn't return observable. Anyway, now it shows some other exception.
```
GOPR7643.JPG  downloading [█████████████████████████████████████████████████████████████████████████████████████████████████] 169/bps 100% 0.0s
IMG_0764.JPG  downloading [██████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░] 52/bps 91% 1.7s
/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:77
    throw e;
    ^

TypeError: this._onNext is not a function
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:1828:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:1762:31)
    at AnonymousObserver.tryCatcher (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:1762:31)
    at LastObserver.completed (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.aggregates.js:1032:17)
    at LastObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:1782:14)
    at LastObserver.tryCatcher (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.completed (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:5897:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:1782:14)
    at Subject.onCompleted (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:5967:19)
    at Subject.tryCatcher (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.completed (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:5897:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:1782:14)
    at AutoDetachObserver.tryCatcher (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.completed (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:5897:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:1782:14)
    at InnerObserver.completed (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:3770:71)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:1782:14)
    at InnerObserver.tryCatcher (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.completed (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:5897:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:1782:14)
    at InnerObserver.completed (/code/cilantro/iogates-transfer/node_modules/rx/dist/rx.js:3770:71)
```

Do you have an idea? Also, I asked `mt` to download `eight (8)` files, however, it downloads them one by one and not in parallel (async). And thanks for the nice library! cheers!
